'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Tracker_of_Time.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adultClaimCheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adultClaimCheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adultCojiro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adultCojiro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adultEyeballFrog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adultEyeballFrog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adultEyeDrops() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adultEyeDrops", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adultGoronsSwordBroken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adultGoronsSwordBroken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adultOddMushroom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adultOddMushroom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adultOddPotion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adultOddPotion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adultPoachersSaw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adultPoachersSaw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adultPocketCucco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adultPocketCucco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adultPocketEgg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adultPocketEgg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adultPrescription() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adultPrescription", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backgroundDungeonItems() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backgroundDungeonItems", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backgroundEquipment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backgroundEquipment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backgroundInventory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backgroundInventory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bombchus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bombchus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bombs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bombs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boomerang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boomerang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleBigPoe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleBigPoe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleBlueFire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleBlueFire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleBluePotion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleBluePotion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleBottledFairy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleBottledFairy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleBug() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleBug", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleFish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleFish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleGreenPotion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleGreenPotion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleLetter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleLetter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleLonLonMilk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleLonLonMilk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleLonLonMilkHalf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleLonLonMilkHalf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottlePoe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottlePoe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottleRedPotion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottleRedPotion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dekuNut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dekuNut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dekuStick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dekuStick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dinsFire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dinsFire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dungeonBossKey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dungeonBossKey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dungeonCompass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dungeonCompass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dungeonMap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dungeonMap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dungeonSmallKey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dungeonSmallKey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property emptySlot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emptySlot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enhancedDefence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enhancedDefence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipBiggoronsSword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipBiggoronsSword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipBrokenKnife() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipBrokenKnife", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipDekuShield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipDekuShield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipGoronTunic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipGoronTunic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipHoverBoots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipHoverBoots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipHylianShield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipHylianShield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipIronBoots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipIronBoots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipKokiriBoots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipKokiriBoots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipKokiriSword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipKokiriSword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipKokiriTunic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipKokiriTunic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipMasterSword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipMasterSword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipMirrorShield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipMirrorShield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipZoraTunic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipZoraTunic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fairyOcarina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fairyOcarina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fairySlingshot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fairySlingshot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property faroresWind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("faroresWind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fireArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fireArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gerudosCard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gerudosCard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gerudosCardEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gerudosCardEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property goldSkulltula() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goldSkulltula", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartContainer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartContainer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hookshot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hookshot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iceArrows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iceArrows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lensOfTruth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lensOfTruth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lightArrows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightArrows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property longshot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("longshot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magicBar0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magicBar0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magicBar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magicBar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magicBar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magicBar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magicBeans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magicBeans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapBlank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapBlank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapBotW0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapBotW0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapBotW1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapBotW1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapBotW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapBotW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapDC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapDC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapDDC0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapDDC0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapDDC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapDDC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapDMC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapDMC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapDMT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapDMT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapDT0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapDT0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapDT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapDT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapDT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapDT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapDT3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapDT3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapDT4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapDT4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapFiT0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapFiT0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapFiT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapFiT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapFiT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapFiT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapFiT3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapFiT3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapFiT4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapFiT4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapFoT0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapFoT0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapFoT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapFoT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapFoT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapFoT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapFoT3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapFoT3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGAC0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGAC0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGAC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGAC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGAC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGAC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGAC3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGAC3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGAC4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGAC4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGAC5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGAC5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGAC51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGAC51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGAC6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGAC6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGAC61() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGAC61", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGAC7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGAC7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGTG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGTG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapGY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapGY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapHC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapHC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapHF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapHF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapHW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapHW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapHW2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapHW2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapIC0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapIC0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapJB0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapJB0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapJB1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapJB1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapKF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapKF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapKV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapKV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapLH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapLH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapLLR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapLLR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapLW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapLW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapMK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapMK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapMK2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapMK2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapMKBA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapMKBA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapMKE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapMKE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapOGC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapOGC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapOToT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapOToT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapSFM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapSFM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapShT0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapShT0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapShT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapShT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapShT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapShT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapShT3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapShT3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapSpT0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapSpT0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapSpT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapSpT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapSpT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapSpT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapSpT3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapSpT3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapToT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapToT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapWaT0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapWaT0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapWaT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapWaT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapWaT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapWaT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapWaT3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapWaT3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapZD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapZD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapZF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapZF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mapZR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mapZR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalFire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalFire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalFireEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalFireEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalForest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalForest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalForestEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalForestEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalLightEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalLightEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalShadow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalShadow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalShadowEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalShadowEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalSpirit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalSpirit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalSpiritEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalSpiritEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalWater() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalWater", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property medalWaterEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("medalWaterEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property megatonHammer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("megatonHammer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nayrusLove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nayrusLove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ocarinaOfTime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ocarinaOfTime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property poh0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poh0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property poh1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poh1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property poh2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poh2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property poh3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poh3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property poh4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("poh4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property songEmptyNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("songEmptyNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property songEmptyWarp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("songEmptyWarp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property songFire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("songFire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property songForest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("songForest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property songLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("songLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property songNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("songNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property songShadow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("songShadow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property songSpirit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("songSpirit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property songWater() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("songWater", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spawnLocations() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spawnLocations", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stoneGoron() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stoneGoron", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stoneGoronEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stoneGoronEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stoneKokiri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stoneKokiri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stoneKokiriEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stoneKokiriEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stoneOfAgony() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stoneOfAgony", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stoneOfAgonyEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stoneOfAgonyEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stoneZora() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stoneZora", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stoneZoraEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stoneZoraEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property trialFire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trialFire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property trialForest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trialForest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property trialLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trialLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property trialShadow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trialShadow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property trialSpirit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trialSpirit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property trialWater() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trialWater", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property triforce() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("triforce", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeBombBag1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeBombBag1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeBombBag2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeBombBag2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeBombBag3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeBombBag3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeBulletBag1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeBulletBag1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeBulletBag2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeBulletBag2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeBulletBag3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeBulletBag3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeGoldenGauntlets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeGoldenGauntlets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeGoldenScale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeGoldenScale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeGoronsBracelet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeGoronsBracelet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeQuiver1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeQuiver1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeQuiver2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeQuiver2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeQuiver3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeQuiver3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeSilverGauntlets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeSilverGauntlets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeSilverScale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeSilverScale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeWallet1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeWallet1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeWallet2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeWallet2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgradeWallet3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgradeWallet3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property worldMap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("worldMap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngBunnyHood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngBunnyHood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngChicken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngChicken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngGerudoMask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngGerudoMask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngGoronMask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngGoronMask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngKeatonMask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngKeatonMask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngMaskOfTruth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngMaskOfTruth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngSkullMask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngSkullMask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngSoldOut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngSoldOut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngSpookyMask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngSpookyMask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngWeirdEgg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngWeirdEgg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngZeldasLetter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngZeldasLetter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property youngZoraMask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("youngZoraMask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
