'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setTheme() As Byte
            Get
                Return CType(Me("setTheme"),Byte)
            End Get
            Set
                Me("setTheme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setSkulltula() As Byte
            Get
                Return CType(Me("setSkulltula"),Byte)
            End Get
            Set
                Me("setSkulltula") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setCow() As Boolean
            Get
                Return CType(Me("setCow"),Boolean)
            End Get
            Set
                Me("setCow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setScrub() As Boolean
            Get
                Return CType(Me("setScrub"),Boolean)
            End Get
            Set
                Me("setScrub") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setShop() As Byte
            Get
                Return CType(Me("setShop"),Byte)
            End Get
            Set
                Me("setShop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setLogic() As Boolean
            Get
                Return CType(Me("setLogic"),Boolean)
            End Get
            Set
                Me("setLogic") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setBombchus() As Boolean
            Get
                Return CType(Me("setBombchus"),Boolean)
            End Get
            Set
                Me("setBombchus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setLensOfTruth() As Boolean
            Get
                Return CType(Me("setLensOfTruth"),Boolean)
            End Get
            Set
                Me("setLensOfTruth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setStoneOfAgony() As Boolean
            Get
                Return CType(Me("setStoneOfAgony"),Boolean)
            End Get
            Set
                Me("setStoneOfAgony") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setHoverTricks() As Boolean
            Get
                Return CType(Me("setHoverTricks"),Boolean)
            End Get
            Set
                Me("setHoverTricks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFewerTunics() As Boolean
            Get
                Return CType(Me("setFewerTunics"),Boolean)
            End Get
            Set
                Me("setFewerTunics") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setOpenKF() As Boolean
            Get
                Return CType(Me("setOpenKF"),Boolean)
            End Get
            Set
                Me("setOpenKF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setOpenZF() As Boolean
            Get
                Return CType(Me("setOpenZF"),Boolean)
            End Get
            Set
                Me("setOpenZF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setRainbow() As Byte
            Get
                Return CType(Me("setRainbow"),Byte)
            End Get
            Set
                Me("setRainbow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setDekuB1Skip() As Boolean
            Get
                Return CType(Me("setDekuB1Skip"),Boolean)
            End Get
            Set
                Me("setDekuB1Skip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setDCStaircase() As Boolean
            Get
                Return CType(Me("setDCStaircase"),Boolean)
            End Get
            Set
                Me("setDCStaircase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setDCSpikeJump() As Boolean
            Get
                Return CType(Me("setDCSpikeJump"),Boolean)
            End Get
            Set
                Me("setDCSpikeJump") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setDCSlingshotSkips() As Boolean
            Get
                Return CType(Me("setDCSlingshotSkips"),Boolean)
            End Get
            Set
                Me("setDCSlingshotSkips") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setDCLightEyes() As Boolean
            Get
                Return CType(Me("setDCLightEyes"),Boolean)
            End Get
            Set
                Me("setDCLightEyes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFoTVines() As Boolean
            Get
                Return CType(Me("setFoTVines"),Boolean)
            End Get
            Set
                Me("setFoTVines") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFoTFrame() As Boolean
            Get
                Return CType(Me("setFoTFrame"),Boolean)
            End Get
            Set
                Me("setFoTFrame") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFoTBackdoor() As Boolean
            Get
                Return CType(Me("setFoTBackdoor"),Boolean)
            End Get
            Set
                Me("setFoTBackdoor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFoTMQPuzzle() As Boolean
            Get
                Return CType(Me("setFoTMQPuzzle"),Boolean)
            End Get
            Set
                Me("setFoTMQPuzzle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFoTMQTwisted() As Boolean
            Get
                Return CType(Me("setFoTMQTwisted"),Boolean)
            End Get
            Set
                Me("setFoTMQTwisted") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFoTMQWell() As Boolean
            Get
                Return CType(Me("setFoTMQWell"),Boolean)
            End Get
            Set
                Me("setFoTMQWell") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFoTLedge() As Boolean
            Get
                Return CType(Me("setFoTLedge"),Boolean)
            End Get
            Set
                Me("setFoTLedge") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setSmallKeys() As Byte
            Get
                Return CType(Me("setSmallKeys"),Byte)
            End Get
            Set
                Me("setSmallKeys") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFiTClimb() As Boolean
            Get
                Return CType(Me("setFiTClimb"),Boolean)
            End Get
            Set
                Me("setFiTClimb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFiTMaze() As Boolean
            Get
                Return CType(Me("setFiTMaze"),Boolean)
            End Get
            Set
                Me("setFiTMaze") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFiTMQClimb() As Boolean
            Get
                Return CType(Me("setFiTMQClimb"),Boolean)
            End Get
            Set
                Me("setFiTMQClimb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFiTRustedSwitches() As Boolean
            Get
                Return CType(Me("setFiTRustedSwitches"),Boolean)
            End Get
            Set
                Me("setFiTRustedSwitches") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFiTMQMazeHovers() As Boolean
            Get
                Return CType(Me("setFiTMQMazeHovers"),Boolean)
            End Get
            Set
                Me("setFiTMQMazeHovers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFiTMQMazeJump() As Boolean
            Get
                Return CType(Me("setFiTMQMazeJump"),Boolean)
            End Get
            Set
                Me("setFiTMQMazeJump") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setWaTTorch() As Boolean
            Get
                Return CType(Me("setWaTTorch"),Boolean)
            End Get
            Set
                Me("setWaTTorch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setWaTDragonDive() As Boolean
            Get
                Return CType(Me("setWaTDragonDive"),Boolean)
            End Get
            Set
                Me("setWaTDragonDive") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setWaTBKR() As Boolean
            Get
                Return CType(Me("setWaTBKR"),Boolean)
            End Get
            Set
                Me("setWaTBKR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setWaTCrackNothing() As Boolean
            Get
                Return CType(Me("setWaTCrackNothing"),Boolean)
            End Get
            Set
                Me("setWaTCrackNothing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setWaTCrackHovers() As Boolean
            Get
                Return CType(Me("setWaTCrackHovers"),Boolean)
            End Get
            Set
                Me("setWaTCrackHovers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setSpTWall() As Boolean
            Get
                Return CType(Me("setSpTWall"),Boolean)
            End Get
            Set
                Me("setSpTWall") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setSpTBombchu() As Boolean
            Get
                Return CType(Me("setSpTBombchu"),Boolean)
            End Get
            Set
                Me("setSpTBombchu") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setSpTMQLowAdult() As Boolean
            Get
                Return CType(Me("setSpTMQLowAdult"),Boolean)
            End Get
            Set
                Me("setSpTMQLowAdult") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setSpTMQSunRoom() As Boolean
            Get
                Return CType(Me("setSpTMQSunRoom"),Boolean)
            End Get
            Set
                Me("setSpTMQSunRoom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShTLensless() As Boolean
            Get
                Return CType(Me("setShTLensless"),Boolean)
            End Get
            Set
                Me("setShTLensless") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShTUmbrella() As Boolean
            Get
                Return CType(Me("setShTUmbrella"),Boolean)
            End Get
            Set
                Me("setShTUmbrella") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShTMQGap() As Boolean
            Get
                Return CType(Me("setShTMQGap"),Boolean)
            End Get
            Set
                Me("setShTMQGap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShTStatue() As Boolean
            Get
                Return CType(Me("setShTStatue"),Boolean)
            End Get
            Set
                Me("setShTStatue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setBotWLensless() As Boolean
            Get
                Return CType(Me("setBotWLensless"),Boolean)
            End Get
            Set
                Me("setBotWLensless") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setBotWDeadHand() As Boolean
            Get
                Return CType(Me("setBotWDeadHand"),Boolean)
            End Get
            Set
                Me("setBotWDeadHand") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setNavi() As Boolean
            Get
                Return CType(Me("setNavi"),Boolean)
            End Get
            Set
                Me("setNavi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setBeans() As Boolean
            Get
                Return CType(Me("setBeans"),Boolean)
            End Get
            Set
                Me("setBeans") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setSalesman() As Boolean
            Get
                Return CType(Me("setSalesman"),Boolean)
            End Get
            Set
                Me("setSalesman") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setWastelandBackstep() As Boolean
            Get
                Return CType(Me("setWastelandBackstep"),Boolean)
            End Get
            Set
                Me("setWastelandBackstep") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setWastelandLensless() As Boolean
            Get
                Return CType(Me("setWastelandLensless"),Boolean)
            End Get
            Set
                Me("setWastelandLensless") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setWastelandReverse() As Boolean
            Get
                Return CType(Me("setWastelandReverse"),Boolean)
            End Get
            Set
                Me("setWastelandReverse") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShTPlatform() As Boolean
            Get
                Return CType(Me("setShTPlatform"),Boolean)
            End Get
            Set
                Me("setShTPlatform") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setIGCMQRustedSwitches() As Boolean
            Get
                Return CType(Me("setIGCMQRustedSwitches"),Boolean)
            End Get
            Set
                Me("setIGCMQRustedSwitches") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setHideSpoiler() As Boolean
            Get
                Return CType(Me("setHideSpoiler"),Boolean)
            End Get
            Set
                Me("setHideSpoiler") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setCucco() As Boolean
            Get
                Return CType(Me("setCucco"),Boolean)
            End Get
            Set
                Me("setCucco") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setWaTDrgnSwitch() As Boolean
            Get
                Return CType(Me("setWaTDrgnSwitch"),Boolean)
            End Get
            Set
                Me("setWaTDrgnSwitch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setSpTLensless() As Boolean
            Get
                Return CType(Me("setSpTLensless"),Boolean)
            End Get
            Set
                Me("setSpTLensless") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShTMQPit() As Boolean
            Get
                Return CType(Me("setShTMQPit"),Boolean)
            End Get
            Set
                Me("setShTMQPit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setBotWMQPits() As Boolean
            Get
                Return CType(Me("setBotWMQPits"),Boolean)
            End Get
            Set
                Me("setBotWMQPits") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setIGCLensless() As Boolean
            Get
                Return CType(Me("setIGCLensless"),Boolean)
            End Get
            Set
                Me("setIGCLensless") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setMap() As Boolean
            Get
                Return CType(Me("setMap"),Boolean)
            End Get
            Set
                Me("setMap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setExpand() As Boolean
            Get
                Return CType(Me("setExpand"),Boolean)
            End Get
            Set
                Me("setExpand") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setFirstTime() As Boolean
            Get
                Return CType(Me("setFirstTime"),Boolean)
            End Get
            Set
                Me("setFirstTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setFiTScarecrow() As Boolean
            Get
                Return CType(Me("setFiTScarecrow"),Boolean)
            End Get
            Set
                Me("setFiTScarecrow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShortForm() As Boolean
            Get
                Return CType(Me("setShortForm"),Boolean)
            End Get
            Set
                Me("setShortForm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property setGSLoc() As Byte
            Get
                Return CType(Me("setGSLoc"),Byte)
            End Get
            Set
                Me("setGSLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setHideQuests() As Boolean
            Get
                Return CType(Me("setHideQuests"),Boolean)
            End Get
            Set
                Me("setHideQuests") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setGTGLensless() As Boolean
            Get
                Return CType(Me("setGTGLensless"),Boolean)
            End Get
            Set
                Me("setGTGLensless") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Tracker_of_Time.My.MySettings
            Get
                Return Global.Tracker_of_Time.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
